### ISSUE TITLE
[redelegation test] redelegation is not possible from the dashboard when not enough fund

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony-dashboard#126]
Available balance for delegation is less than 0.xx
undelegated in progress of 2500 : 
![image](https://user-images.githubusercontent.com/35721420/92777670-fe19b200-f3d2-11ea-95b4-9e1671493c56.png)

trying to redelegate the 2500 to another validator, however dashboard still says Not enough funds to delegate, minimum 1000 ONEs

![image](https://user-images.githubusercontent.com/35721420/92774810-674bf600-f3d0-11ea-86a0-5bae90073dc6.png)

Added 1000 in the account and still can't redelegate 2500:
![image](https://user-images.githubusercontent.com/35721420/92777421-c448ab80-f3d2-11ea-89aa-d1aa3a724b82.png)

trying to redelegate only 1000 (ie what I have in my wallet) works as expected, only the undelegated token were used for delegation towards the new validator

**Comment by rlan35** [comment]
@potvik we will need to take care of this condition after redelegation is enabled. Basically the check should be amount <= balance + undelegated tokens that's more than 1 epoch old. For details about how redelegation works: https://www.notion.so/harmonyone/Redelegation-7-Epoch-Locking-Release-5bb66b96b900451c9931f8cc11e1e7fc

**Comment by sophoah** [comment]
@rlan35 we need the same fix on hmy cli as well, i haven't create the issue yet, let me know if there is need one

**Comment by sophoah** [comment]
issue fixed
