### ISSUE TITLE
shard 1 and 2 status not reflected in the testnet explorer

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-dashboard#16]
This is a known issue, but it only exists in our internal network. 

Desc
In the main page of explorer (https://explorer.testnet.harmony.one/#/), it only shows the live status of shard 0, although shard 1 and 2 are online, and generating blocks. 

 
![Screen Shot 2020-01-08 at 2 16 22 PM](https://user-images.githubusercontent.com/5258417/72021036-f1303780-3221-11ea-8512-d39f19e7e4a9.png)

**Comment by AndyBoWu** [comment]
to check out the status of shard 1 and shard 2:

https://explorer.testnet.harmony.one/#/shard/1

https://explorer.testnet.harmony.one/#/shard/2

**Comment by LeoHChen** [comment]
As @rlan35 said, the root cause is the front page was sorted by block height, not by timestamp.  So, the higher block shows up on shard0.  We need to sort it by timestamp.
