### ISSUE TITLE
BUG - tx output is not consistent

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony-dashboard#36]
Hi Team,

Have a look at those explorer output which shows different output :

shows from/to shard:
https://explorer.harmony.one/#/tx/0xe84a32a89551566183ee0704fe7fc0e86c91e5208ee9fd1faaf6fae29f173b90
https://explorer.harmony.one/#/tx/0xdb2df597ca549e931686ec4e47442382d065fc9c283a58d0a12e90ba347b454b

doesn't show:
https://explorer.harmony.one/#/tx/0x5fef930ec7059931106880b65a13b5796fc59c80ea0d8f21b158e71e3623eaaa
https://explorer.harmony.one/#/tx/0x197ec79efb19855abbb6ef568d78d6e2d05815ded0a823b7ed986122f4921453

Soph

**Comment by Daniel-VDM** [comment]
Just checked the hashes, the bottom two are same shard transactions and thus don't have a to and from shard field. I believe this is the expected behavior.

**Comment by sophoah** [comment]
Thanks @Daniel-VDM would just close it then.
