### ISSUE TITLE
Failure txs are not searchable on explorer

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/harmony-dashboard#45]
Failure txs are not searchable using the Search box as shown by the image bellow:
![Untitled](https://user-images.githubusercontent.com/7217595/73310115-5f08c700-4202-11ea-8496-d981bc1d294f.jpg)

Though, if i submit the same tx via parameter using the URL it finds it:
![Untitled2](https://user-images.githubusercontent.com/7217595/73310167-79db3b80-4202-11ea-94ba-f03d5df5349a.jpg)

Tx used to test it: 0x9a17e29cb266b60bc60bf1069cdb2f4b0db5f3b7a75f55e60de8d25bd05b2fdb
Url: https://explorer.testnet.harmony.one/

To reproduce the test, you can use any tx that is shown on testnet using the command bellow:
`./hmy --node=https://api.s0.b.hmny.io/ failures plain`

**Comment by denniswon** [comment]
This issue has been already fixed.
![Screen Shot 2020-03-14 at 2 59 17 AM](https://user-images.githubusercontent.com/3278577/76679725-d7073280-659f-11ea-8d86-7a9ab2582754.png)
