### ISSUE TITLE
[Explorer] OSTN Explorer UI bug

### ISSUE THREAD

**Issue by janet-harmony** [harmony-one/harmony-dashboard#50]
OSTN block explorer, when viewing a shard page
https://explorer.os.hmny.io/#/shard/0
<img width="499" alt="Screen Shot 2020-03-13 at 8 06 58 PM" src="https://user-images.githubusercontent.com/56005637/76673837-5546e300-6566-11ea-9012-cb95c9278813.png">

**Comment by denniswon** [comment]
fixed
![Screen Shot 2020-03-14 at 2 56 11 AM](https://user-images.githubusercontent.com/3278577/76679637-5ea07180-659f-11ea-99a3-3bb871af226f.png)
