### ISSUE TITLE
[Explorer] OSTN Explorer Shard 0 missing blocks

### ISSUE THREAD

**Issue by janet-harmony** [harmony-one/harmony-dashboard#52]
Missing every block that ends in 2, 4, 6, & 8.
Link: https://explorer.os.hmny.io/#/shard/0
<img width="451" alt="Screen Shot 2020-03-17 at 3 24 09 PM" src="https://user-images.githubusercontent.com/56005637/76911196-7280f780-686d-11ea-8acb-8e25c19594b2.png">

**Comment by sophoah** [comment]
looks like this issues is fixed. @janet-harmony can you close it ? Thanks
