### ISSUE TITLE
some address have lost tx in explorer

### ISSUE THREAD

**Issue by songgeng87** [harmony-one/harmony-dashboard#55]
https://explorer.harmony.one/#/address/one15043fwwtms8pxzderqvjlf9n2q57m7hyx740v2

in the explorer, the tx with nonce 0x0 and 0x4 are missing

**Comment by LeoHChen** [comment]
it seems all our explorer nodes are running in archival mode. 

then we need to figure out

* does the RPC calls return all the tx for this address?
* does we store the tx data in the db if RPC returned properly?
* or just display issue.

**Comment by mikedoan** [comment]
yeah, 0x0 and  0x3 and others are missing

**Comment by mikedoan** [comment]
GetTransactionsHistory return 11 txns for one15043fwwtms8pxzderqvjlf9n2q57m7hyx740v2, where 7 of them were with one15043fwwtms8pxzderqvjlf9n2q57m7hyx740v2 as senders , the rest of 4 were with that address as receivers


```
txn 0x7b19fed47a02422bbab5205c9cd3650aecb87ed6fe9a2a86135f9595cc0a0d3a for 0x1
0x5d7f4f645ffbd8a5ad07b8060c948f3402bc4f7eb6c225596a8951f33c17ff02 for 0x2
0x89087765824e63e7d60ec2453a58fa14ee4ec2b01f43d7805e2f0a87ac203df9 for 0x4
0x7f774757bc9eed08f9213045f4565e67ae8528dabbddc352c645ea690dd0bda4 for 0x5
0xe410fb60b9b1e2936da89ee25cbcf97bcebabc7993d55113404d60e34b55a6e1 for 0x7
0xb10ccf71b1eacd9bd2688d6c00c18f4d67b0d9c4728c1dea14bab3d20f4154d8 for 0x8
0x62d579b9b2dcfce93f3f074dafb213f0e24cfa873d8466260324f5368d6a1d8c for 0x9
```

missing 0x0, 0x3, 0x6,

**Comment by LeoHChen** [comment]
so are we missing the data in blockchain or what?

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony/pull/2624

**Comment by denniswon** [comment]
@songgeng87 @mikedoan is this still an issue? or resolved?

**Comment by songgeng87** [comment]
it is still an issue, not resolved

**Comment by denniswon** [comment]
I can't confirm the issue. The link above https://explorer.harmony.one/#/address/one15043fwwtms8pxzderqvjlf9n2q57m7hyx740v2 seems like all txns are there. Please re-confirm. @songgeng87

**Comment by denniswon** [comment]
@songgeng87 confirmed that this bug is fixed. closing.
