### ISSUE TITLE
[Explorer] Transaction status is "Unknown" for all transactions

### ISSUE THREAD

**Issue by janet-harmony** [harmony-one/harmony-dashboard#56]
On OSTN explorer, all the transactions have status "Unknown", even though they are successful.
![Screen Shot 2020-03-28 at 10 50 11 AM](https://user-images.githubusercontent.com/56005637/77829880-18402c00-70e2-11ea-967a-01d66047b7a9.png)

**Comment by denniswon** [comment]
fixed https://github.com/harmony-one/harmony-dashboard-backend/pull/38
