### ISSUE TITLE
collect rewards doesnt show value/amount

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony-dashboard#67]
Explorer doesnt show amount for collect rewards staking transactions:

https://explorer.os.hmny.io/#/staking-tx/0x0146ca0524e8f5247a5ada6a4c23d15384d7db77aaf6a6c1e9925670089c5a77

![scr](https://user-images.githubusercontent.com/55639830/78728095-bcbe3b80-7936-11ea-8035-c6cbefe3839b.png)

**Comment by Dewansahil** [comment]
@mindstyle85 this is expected right now since the collect rewards transaction doesn't have a value attached on-chain. @rlan35 and @gupadhyaya recommended that we should include the collect reward value in the cross-link and then use that for displaying on the transaction status page.
cc @denniswon
