### ISSUE TITLE
Transaction redirect from mathwallet successful transaction link doesn't update properly 

### ISSUE THREAD

**Issue by Dewansahil** [harmony-one/harmony-dashboard#68]
Staking transaction from staking chrome extension goes to regular txn page on block explorer when link clicked

![Screen Shot 2020-04-07 at 5 11 10 PM](https://user-images.githubusercontent.com/45057123/78730827-cb82ff00-78f2-11ea-97be-a3b4f5bd5ce4.png)

![Screen Shot 2020-04-07 at 5 09 49 PM](https://user-images.githubusercontent.com/45057123/78730809-bf973d00-78f2-11ea-8e8b-3392a9184fee.png)

**Comment by denniswon** [comment]
this should be updated from staking chrome extension. @mikedoan 
should use /stakingTx endpoint not /tx.

**Comment by denniswon** [comment]
https://github.com/harmony-one/staking-dashboard/pull/336 will fix this issue.

**Comment by denniswon** [comment]
This has been fixed, and the fix is deployed.
