### ISSUE TITLE
transaction number showing not correct

### ISSUE THREAD

**Issue by ivorytowerdds** [harmony-one/harmony-dashboard#88]
In the staking dashboard, the total txs from all shards doesn't match the number the total txs of the address.
![image](https://user-images.githubusercontent.com/34232522/81023459-50473700-8e25-11ea-87d8-9915cde919c3.png)

There are two rpc call, hmy_getTransactionCount and hmy_getTransactionsCount the first one is from blockchain, and the second one is from the explorer db, my assumption is that the address txs and each shard txs are using different rpc calls, which caused the error. I think there may be some error in one of the rpc calls.

![image](https://user-images.githubusercontent.com/34232522/81023468-5c32f900-8e25-11ea-9e9c-0d2537eb9da1.png)

**Comment by denniswon** [comment]
The fix has been deployed on backend. Please let me know if issues persists.
https://github.com/harmony-one/harmony-dashboard-backend/issues/35
@ivorytowerdds

**Comment by denniswon** [comment]
![Screen Shot 2020-05-21 at 4 35 12 PM](https://user-images.githubusercontent.com/3278577/82616172-51949580-9b81-11ea-90e0-a6c9990fedc7.png)

Note that for the address overall txs and staking txns count on address page will need front end update to be fixed. @potvik
