### ISSUE TITLE
use systemd service for both FE/BE of explorer

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-dashboard#91]
We need to use systemd service to manage both the Frontend and Backend of explorer itself.

Both of them are running using tmux session right now. I remember I had created a script for @denniswon to use `nohup` on the explorer on OSTN for easy restart.  Anyway, we should use systemd to manage them.

**Comment by SebastianJ** [comment]
We need to upgrade the instance OS used for the explorer backend/frontend since they currently run Amazon Linux 1 which doesn't have Systemd installed:

```
$ systemctl --version
-bash: systemctl: command not found

$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

**Comment by SebastianJ** [comment]
Started on an initial frontend/fe systemd unit file here:
https://gist.github.com/SebastianJ/ccb7c7e92914a07a8a183dc7fce33478

**Comment by LeoHChen** [comment]
The migration plan
- [ ] start a new ec2 instance with latest amazon linux2
- [ ] install all the needed npm packages, should use either docker or an ansible playbook to manage the packages (docker file or ansible-playbook should be checked into the repo)
- [ ] download all latest packages of explorer FE/BE
- [ ] copy the SSL certificate from old server to the new one
- [ ] use systemd service to manage FE/BE (also check into the repo)
- [ ] test out the FE/BE separately, IP/Port
- [ ] announce the temporary shutdown of the explorer service
- [ ] stop the FE/BE on the production server
- [ ] reassign the elastic IP to the new server
- [ ] should be live now

**Comment by LeoHChen** [comment]
added a new server running Amazon Linux 2, 34.209.169.84

**Comment by LeoHChen** [comment]
same security group is used for the new server.

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/experiment-deploy/pull/332
Ansible playbook/role to support package installation on the server.

**Comment by LeoHChen** [comment]
FE package can be installed using git in the ansible script.

however, BE package is still in a private repo, which requires credential setup on the server. Won't do that in ansible.

**Comment by LeoHChen** [comment]
However, when I was testing run the frontend server, I hit the following errors, @denniswon , any help?

```
[ec2-user@ip-172-31-2-227 harmony-dashboard]$ sudo npm run build

> harmony-website@1.0.0 build /home/ec2-user/harmony-dashboard
> vue-cli-service build

/home/ec2-user/harmony-dashboard/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/harmony-dashboard/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)

npm ERR! Linux 4.14.173-137.229.amzn2.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! harmony-website@1.0.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the harmony-website@1.0.0 build script 'vue-cli-service build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the harmony-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs harmony-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls harmony-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/harmony-dashboard/npm-debug.log
```

**Comment by denniswon** [comment]
@LeoHChen did you run npm install to install all npm packages involved in the project?

**Comment by jhd2best** [comment]
already migrate testnet/mainnet explorer to new servers.
